#
# Component generated by Impac! Widget Generator!
#
module = angular.module('impac.components.widgets.legal-invoiced-hours', [])
module.controller('WidgetLegalInvoicedHoursCtrl', ($scope, $q, ChartFormatterSvc) ->

  w = $scope.widget

  # Define settings
  # --------------------------------------
  $scope.orgDeferred = $q.defer()
  $scope.chartDeferred = $q.defer()
  $scope.datesPickerDeferred = $q.defer()

  settingsPromises = [
    $scope.orgDeferred.promise,
    $scope.chartDeferred.promise,
    $scope.datesPickerDeferred.promise
  ]

  # Widget specific methods
  # --------------------------------------
  w.initContext = ->
    w.metadata.hist_parameters = {
      from: moment().startOf('year').format('YYYY-MM-DD'),
      to: moment().format('YYYY-MM-DD'),
      period: 'RANGE'
    }
    $scope.isDataFound = true


  # Chart formating function
  # --------------------------------------
  $scope.drawTrigger = $q.defer()
  # Format the widget content data for ChartJS.
  w.format = ->
    $scope.isDataFound = true
    inputData = [
      { label: 'Not invoiced', value: 5400 },
      { label: 'Invoiced', value: 9600 }
    ]
    chartData = ChartFormatterSvc.pieChart(inputData, { currency: 'h' }, true)
    $scope.drawTrigger.notify(chartData)

  $scope.positiveColor = ->
    ChartFormatterSvc.getPositiveColor()

  $scope.negativeColor = ->
    ChartFormatterSvc.getNegativeColor()
  

  # Widget is ready: can trigger the "wait for settings to be ready"
  # --------------------------------------
  $scope.widgetDeferred.resolve(settingsPromises)
)
module.directive('widgetLegalInvoicedHours', ->
  return {
    restrict: 'A',
    controller: 'WidgetLegalInvoicedHoursCtrl'
  }
)
