#
# Component generated by Impac! Widget Generator!
#
module = angular.module('impac.components.widgets.accounts-cash-balance', [])
module.controller('WidgetAccountsCashBalanceCtrl', ($scope, $q, ChartFormatterSvc) ->

  w = $scope.widget

  # Define settings
  # --------------------------------------
  $scope.orgDeferred = $q.defer();

  settingsPromises = [
    $scope.orgDeferred.promise,
  ]

  # Widget specific methods
  # --------------------------------------
  w.initContext = ->
    $scope.isDataFound = w.content?

    myChart = Highcharts.chart 'cashBalanceChart', {
      chart: 
        type: 'line'
      title: null
      legend:
        layout: 'vertical'
        align: 'left'
        verticalAlign: 'middle'
      series: w.content.chart.series
      xAxis:
        categories: w.content.chart.labels
      yAxis:
        title:
          text: 'Balance'
    }


  # Widget is ready: can trigger the "wait for settings to be ready"
  # --------------------------------------
  $scope.widgetDeferred.resolve(settingsPromises)
)
module.directive('widgetAccountsCashBalance', ->
  return {
    restrict: 'A',
    controller: 'WidgetAccountsCashBalanceCtrl'
  }
)
