language: node_js
node_js:
  - "5.6.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  # - npm install -g gulp
  - node_modules/.bin/bower install -f
script:
  - node_modules/.bin/gulp build:dist
  - node_modules/.bin/gulp test
addons:
  chrome: stable
