language: node_js
node_js:
  - "6.11.0"
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  # - npm install -g gulp
  - node_modules/.bin/bower install -f
script:
  - node_modules/.bin/gulp build:dist
  - node_modules/.bin/gulp test
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
