#
# Component generated by Impac! Widget Generator!
#
module = angular.module('impac.components.widgets.legal-news-feed', [])
module.controller('WidgetLegalNewsFeedCtrl', ($scope, $q, $http, $timeout, ImpacAssets, ImpacWidgetsSvc) ->

  w = $scope.widget

  # Define settings
  # --------------------------------------
  $scope.orgDeferred = $q.defer()
  $scope.keywords = {
    tags: []
    init: ->
      this.tags = w.metadata.keywords || _.map(['affaire', 'justice', 'jugement', 'loi'], (t) -> { text: t })
    format: ->
      return '' unless this.tags
      tags = _.map this.tags, (t) -> t.text
      tags.join('%20')
  }
  $scope.loaderUrl = "#{ImpacAssets.get('defaultImagesPath')}/double-ring-loader.gif"
  $scope.rssId = "rss-feeds-#{w.id}"

  settingsPromises = [
    $scope.orgDeferred.promise
  ]

  BASE_URL = 'https://news.google.com/news/rss/headlines/section/q'

  loadRss = ->
    $scope.loading = true

    rssElem = $("##{$scope.rssId}")
    rssElem.empty()

    rssUrl = "#{BASE_URL}/#{$scope.keywords.format()}/Legal?ned=fr&hl=fr"
    rssElem.rss(
      rssUrl,
      {
        limit: 10
        dateFormat: 'DD/MM/YYYY'
        ssl: true
        entryTemplate: '
          <div class="row entry">
            <div class="col-xs-4 text-center">
              {teaserImage}
            </div>
            <div class="col-xs-8">
              <a href="{url}">{date} - {title}</a>
              <br/>
              {shortBodyPlain}
            </div>
          </div>
        '
      },
      -> $timeout(-> $scope.loading = false)
    )

  $scope.reload = (tag) ->
    loadRss()
    ImpacWidgetsSvc.update(w, metadata: { keywords: $scope.keywords.tags }, false)

  # Widget specific methods
  # --------------------------------------
  w.initContext = ->
    $scope.keywords.init()
    loadRss()
    $scope.isDataFound = true

  # Widget is ready: can trigger the "wait for settings to be ready"
  # --------------------------------------
  $scope.widgetDeferred.resolve(settingsPromises)
)

module.directive('widgetLegalNewsFeed', ->
  return {
    restrict: 'A',
    controller: 'WidgetLegalNewsFeedCtrl'
  }
)
