#
# Component generated by Impac! Widget Generator!
#
module = angular.module('impac.components.widgets.legal-signed-documents', [])
module.controller('WidgetLegalSignedDocumentsCtrl', ($scope, $q, ImpacAssets) ->

  w = $scope.widget

  # Define settings
  # --------------------------------------
  $scope.orgDeferred = $q.defer();

  settingsPromises = [
    $scope.orgDeferred.promise,
  ]

  $scope.invoiceSamplePath = "#{ImpacAssets.get('defaultImagesPath')}/invoice-sample.png"
  $scope.docSamplePath = "#{ImpacAssets.get('defaultImagesPath')}/document-sample.jpg"
  $scope.gDriveLogoPath = "#{ImpacAssets.get('defaultImagesPath')}/gdrive-logo.png"
  $scope.showInvoice = false
  $scope.showDoc = false

  $scope.documents = [
    { customer: 'Sébastien Gabriel', name: 'Devis #3540021-QUOT' , status: 'signed' },
    { customer: 'Sébastien Gabriel', name: 'Accord modif. honoraires', status: 'signed' },
    { customer: 'Sébastien Gabriel', name: 'Clause confid.', status: 'unsigned' },
    { customer: 'Catherine Ethan', name: 'Devis #5549835-QUOT', status: 'signed' },
    { customer: 'Catherine Ethan', name: 'Facture finale', status: 'unsigned' },
    { customer: 'Justine Marie', name: 'Clauses divorce revues', status: 'unsigned' },
    { customer: 'Mathias Louis', name: 'Acquisition appartement rue Michel', status: 'signed' },
    { customer: 'Gautier Michaud', name: 'Rapport de litige', status: 'signed' },
    { customer: 'Gautier Michaud', name: 'Devis #5598987-QUOT', status: 'unsigned' },
    { customer: 'Gautier Michaud', name: 'Facture initiale', status: 'unsigned' },
    { customer: 'Joël Descoteaux', name: 'Facture initiale', status: 'unsigned' },
    { customer: 'Judith Blaise', name: 'Accord de principe procedure divorce', status: 'n/a' },
    { customer: 'Judith Blaise', name: 'Facture initiale', status: 'unsigned' },
    { customer: 'Gilberte Cousineau', name: 'Cloture litige succession', status: 'signed' },
    { customer: 'Arlette Gagne', name: 'Rapport de proces rupture CGV', status: 'signed' },
    { customer: 'Daphné Plourde', name: 'Devis #54654616-QUOT', status: 'signed' },
    { customer: 'Daphné Plourde', name: 'Facture initiale', status: 'unsigned' },
    { customer: 'Daphné Plourde', name: 'Devis #11454796-QUOT', status: 'unsigned' },
    { customer: 'Daphné Plourde', name: 'Accord de principe - confid.', status: 'n/a' },
    { customer: 'Pénélope Salomon', name: 'Facture finale', status: 'signed' },
    { customer: 'Amédée Paul', name: 'Accord de principe', status: 'n/a' },
    { customer: 'Édouard Jordan', name: 'Honoraires session conseil', status: 'signed' },
    { customer: 'Geoffroy Richard', name: 'Formation pole juridique', status: 'signed' }
  ]

  $scope.ascending = true
  $scope.sortedColumn = 'customer'

  # Widget specific methods
  # --------------------------------------
  w.initContext = ->
    $scope.isDataFound = true

  $scope.sort = (col) ->
    if $scope.sortedColumn == col
      $scope.ascending = !$scope.ascending
    else
      $scope.ascending = true
      $scope.sortedColumn = col
    sortBy( (el) -> el[$scope.sortedColumn] )

  sortBy = (getElem) ->
    $scope.documents.sort (a, b) ->
      res = if getElem(a) > getElem(b) then 1
      else if getElem(a) < getElem(b) then -1
      else 0
      res *= -1 unless $scope.ascending
      return res

  $scope.preview = (doc) ->
    if doc.name.match('Facture') || doc.name.match('Devis')
      $scope.showInvoice = true
      $scope.showDoc = false
    else
      $scope.showInvoice = false
      $scope.showDoc = true

  # Widget is ready: can trigger the "wait for settings to be ready"
  # --------------------------------------
  $scope.widgetDeferred.resolve(settingsPromises)
)
module.directive('widgetLegalSignedDocuments', ->
  return {
    restrict: 'A',
    controller: 'WidgetLegalSignedDocumentsCtrl'
  }
)
