#
# Component generated by Impac! Widget Generator!
#
module = angular.module('impac.components.widgets.sales-average-purchase-size', [])
module.controller('WidgetSalesAveragePurchaseSizeCtrl', ($scope, $q, $filter, ImpacWidgetsSvc, ImpacAssets, HighchartsFactory, ImpacUtilities) ->

  w = $scope.widget
  $scope.isChartDisplayed = true

  # Define settings
  # --------------------------------------
  $scope.orgDeferred = $q.defer();
  settingsPromises = [$scope.orgDeferred.promise]

  # Time management
  todayUTC = moment().startOf('day').add(moment().utcOffset(), 'minutes')

  # Timestamps stored in the back-end are in UTC => the filter on the date must be UTC too
  dateFilter = (timestamp) ->
    pickedDate = moment.utc(timestamp)
    if pickedDate <= todayUTC then "lte #{pickedDate.format('YYYY-MM-DD')}" else pickedDate.format('YYYY-MM-DD')

  imgSrc = (name) ->
    ImpacAssets.get(_.camelCase(name + 'ArrowUp'))

  # Unique identifier for the chart object in the DOM
  $scope.chartId = ->
    "averagePurchaseSizeChart-#{w.id}"

  # # == Sub-Components - Needed? =============================================================
  $scope.chartDeferred = $q.defer()

  # == Chart Events Callbacks =====================================================================
  # Sets the transactions list resources type and displays it
  onClickBar = (event) ->
    $scope.isChartDisplayed = false

  rendererCallback = (chart) ->
    console.log("#{imgSrc('green')}")
    point = chart.series[3].yData[0]
    text = "<h4> Insight Data </h4>
            <br>
            <h5> Previous Month: #{point} </h5>"
    # Make the positioning dynamic
    chart.renderer.image("#{imgSrc('green')}", 30, 400, 20, 20)
      .attr(
        zIndex: 7
      ).add()
    chart.renderer.label(text, 20, 400, 'rect')
      .css(color: '#E2E2E2')
      .attr(
        fill: 'rgba(0, 0, 0, 0.75)'
        padding: 8
        r: 5
        zIndex: 6
      ).add()
    return

  # == Directive Events Callbacks =====================================================================
  $scope.onButtonBack = () ->
    $scope.isChartDisplayed = true

  # Widget specific methods
  # --------------------------------------
  w.initContext = ->
    $scope.isDataFound = w.content?

  w.format = ->
    # Instantiate and render chart
    options =
      chartType: 'line'
      chartOnClickCallbacks: []
      currency: w.metadata.currency
      showToday: true
      showLegend: true

    $scope.chart = new HighchartsFactory($scope.chartId(), w.content.chart, options)

    $scope.chart.formatters = ->
        currency = @options.currency
        xAxisLabels =
          labels:
            formatter: ->
              if (this.chart.rangeSelector.options.selected >= 3)
                moment.utc(this.value).format('MMM YYYY')
              else
                moment.utc(this.value).format('DD MMM')
        yAxisLabels =
          labels:
            formatter: ->
              $filter('mnoCurrency')(this.value, currency, false)
        xAxis: angular.merge([w.content.chart.xAxis[0]], [xAxisLabels])
        yAxis: angular.merge([w.content.chart.yAxis[0]], [yAxisLabels])
        rangeSelector:
          selected: 5

    $scope.chart.render(w.content.chart, options, rendererCallback)

    # Add events callbacks to chart object
    $scope.chart.addSeriesEvent('click', onClickBar)

    # Notifies parent element that the chart is ready to be displayed
    $scope.chartDeferred.notify($scope.chart)

  $scope.widgetDeferred.resolve(settingsPromises)
)
module.directive('widgetSalesAveragePurchaseSize', ->
  return {
    restrict: 'A',
    controller: 'WidgetSalesAveragePurchaseSizeCtrl'
  }
)
