#
# Component generated by Impac! Widget Generator!
#
module = angular.module('impac.components.widgets.sales-average-purchase-size', [])
module.controller('WidgetSalesAveragePurchaseSizeCtrl', ($scope, $q, ImpacWidgetsSvc, ImpacAssets, HighchartsFactory, BoltResources) ->

  w = $scope.widget

  # Define settings
  # --------------------------------------
  $scope.orgDeferred = $q.defer();
  settingsPromises = [$scope.orgDeferred.promise]

  # Time management
  todayUTC = moment().startOf('day').add(moment().utcOffset(), 'minutes')

  # Timestamps stored in the back-end are in UTC => the filter on the date must be UTC too
  dateFilter = (timestamp) ->
    pickedDate = moment.utc(timestamp)
    if pickedDate <= todayUTC then "lte #{pickedDate.format('YYYY-MM-DD')}" else pickedDate.format('YYYY-MM-DD')

  # Unique identifier for the chart object in the DOM
  $scope.chartId = ->
    "averagePurchaseSizeChart-#{w.id}"

  # # == Sub-Components - Needed? =============================================================
  # $scope.chartDeferred = $q.defer()
  # $scope.chartPromise = $scope.chartDeferred.promise

  # Widget specific methods
  # --------------------------------------
  w.initContext = ->
    $scope.isDataFound = w.content?

    # Hide Cash Flow series returned by the API
    averagePurchaseSize = _.find w.content.chart.series, (serie) ->
      serie.name == "Purchase Size"
    averagePurchaseSize.data = []
    averagePurchaseSize.type = 'area'
    averagePurchaseSize.showInLegend = false

    # Fetch Merchant from Bolt and save ids?
    # TODO: needed?
    # BoltResources.index(
    #   w.metadata.bolt_path, 'merchants'
    # ).then((response) -> $scope.merchants = response.data)

  w.format = ->

    # Instantiate and render chart
    options =
      chartType: 'line'
      chartOnClickCallbacks: []
      currency: w.metadata.currency
      showToday: true
      showLegend: true

    $scope.chart ||= new HighchartsFactory($scope.chartId(), w.content.chart, options)
    $scope.chart.render(w.content.chart, options)

    # Add events callbacks to chart object
    # Needed?
    # $scope.chart.addCustomLegend(legendFormatter)
    # $scope.chart.addSeriesEvent('click', onClickBar)

    # Notifies parent element that the chart is ready to be displayed
    $scope.chartDeferred.notify($scope.chart)

  $scope.widgetDeferred.resolve(settingsPromises)
)
module.directive('widgetSalesAveragePurchaseSize', ->
  return {
    restrict: 'A',
    controller: 'WidgetSalesAveragePurchaseSizeCtrl'
  }
)
